### ISSUE TITLE
/root/explorer/lib/database.js:642 lib.syncLoop(block.tx.length, function (subloop){

### ISSUE THREAD

**Issue by leegod** [iquidus/explorer#173] opened 2018-03-27 09:01 UTC
I met following error when I do node scripts/sync.js index reindex 

TypeError: Cannot read property 'length' of undefined
    at /root/explorer/lib/database.js:642:36
    at Request._callback (/root/explorer/lib/explorer.js:107:14)
    at Request.self.callback (/root/explorer/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/root/explorer/node_modules/request/request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/root/explorer/node_modules/request/request.js:965:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

I felt misfortune when I install npm by [ sudo npm install forever -g ]
following errors.

npm WARN optional Skipping failed optional dependency /forever/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3

**Comment by TheHolyRoger** [comment] 2019-12-25 01:06
Duplicate of https://github.com/iquidus/explorer/issues/56

**Closed by TheHolyRoger** 2019-12-25 01:06 UTC
