### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by sp00lin9** [iquidus/explorer#118] opened 2017-12-06 15:26 UTC
Hello All! Thank you for the great work & support! Wondering if anyone has ran into this issue before - 

/explorer/lib/explorer.js:344
          module.exports.syncLoop(tx.vout.length, function (loop) {
                                         ^
TypeError: Cannot read property 'length' of undefined
    at /root/explorer/lib/explorer.js:344:42
    at Request._callback (/root/explorer/lib/explorer.js:114:14)
    at Request.self.callback (/root/explorer/node_modules/request/request.js:187:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/root/explorer/node_modules/request/request.js:1044:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/root/explorer/node_modules/request/request.js:965:12)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Whatever I try, I cant get it to sync past a block 171620. Neither index update, index reindex & index check will get past that block 171620. If anyone can point me in the right direction I'd appreciate it.

Thank you!

**Comment by sp00lin9** [comment] 2017-12-07 01:26
I can provide the output of the getblockbynumber for 171620 & 171621 if needed. Please let me know.

Thanks.

**Comment by sp00lin9** [comment] 2017-12-07 17:35
Just found this in my explorer output as I try to run the update - 

{ Error: No information available about transaction
    at /root/explorer/node_modules/bitcoin-node-api/node_modules/bitcoin/lib/jsonrpc.js:99:19
    at Array.forEach (<anonymous>)
    at IncomingMessage.<anonymous> (/root/explorer/node_modules/bitcoin-node-api/node_modules/bitcoin/lib/jsonrpc.js:96:15)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: -5 }

**Comment by sp00lin9** [comment] 2017-12-08 18:44
It will oddly enough let me manually add blocks to the block explorer using the api, but wont pick them up on its own after block 171620.

Anyone have even the slightest clue?

**Comment by erfan007p** [comment] 2017-12-08 20:13
try to reindex your daemon and run index reindex or index check

**Comment by sp00lin9** [comment] 2017-12-08 20:31
I've tried deleting & redownloading the block chain for the daemon, then running index reindex & it still gives me 

/explorer/lib/explorer.js:344
module.exports.syncLoop(tx.vout.length, function (loop) {
^
TypeError: Cannot read property 'length' of undefined
at /root/explorer/lib/explorer.js:344:42
at Request._callback (/root/explorer/lib/explorer.js:114:14)
at Request.self.callback (/root/explorer/node_modules/request/request.js:187:22)
at emitTwo (events.js:125:13)
at Request.emit (events.js:213:7)
at Request. (/root/explorer/node_modules/request/request.js:1044:10)
at emitOne (events.js:115:13)
at Request.emit (events.js:210:7)
at IncomingMessage. (/root/explorer/node_modules/request/request.js:965:12)
at emitNone (events.js:110:20)
at IncomingMessage.emit (events.js:207:7)
at endReadableNT (_stream_readable.js:1059:12)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickCallback (internal/process/next_tick.js:180:9)

index check also gives me this error ^^^

I havent tried starting the daemon with the -reindex flag, then running index reindex, so I'll try that, wouldnt hurt at this point lol

**Comment by sp00lin9** [comment] 2017-12-11 15:33
Well, I've tried everything above with no luck. Not sure what else to do...

**Comment by Igor-san** [comment] 2017-12-11 16:17
try in file explorer.js in function
syncLoop: function (iterations, process, exit) {
....
if (index% 100 === 0) {// clear stack


change value 100 to 30 (or other smaller)

**Comment by sp00lin9** [comment] 2017-12-11 17:37
Thanks for the suggestion, I'm reindexing with the changes now & my fingers crossed! I'll report back with what I find.

**Comment by sp00lin9** [comment] 2017-12-12 16:05
I tried to update first then reindex with the same result /:

**Comment by sp00lin9** [comment] 2017-12-13 01:53
Looks like block 171621 has a non-standard transaction, but this commit looks like it should've taken care of this issue?

https://github.com/iquidus/explorer/commit/2c0cf364e1bb609ff362e8da1836719d63eae228

**Comment by rupaya-project** [comment] 2018-02-05 17:12
did anyone figure out what the issue is ? is there any fix ?

**Comment by WebsVentoVishal** [comment] 2018-02-28 06:07
> **Same` issue. Anyone have solution??**

TypeError: Cannot read property 'length' of undefined
    at C:\Users\Vishal\Downloads\explorer\lib\database.js:642:37
    at Request._callback (C:\Users\Vishal\Downloads\explorer\lib\explorer.js:107:14)
    at Request.self.callback (C:\Users\Vishal\Downloads\explorer\node_modules\request\request.js:187:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Vishal\Downloads\explorer\node_modules\request\request.js:1044:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\Vishal\Downloads\explorer\node_modules\request\request.js:965:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by blakey12345** [comment] 2018-03-11 06:33
module.exports.get_rawtransaction(input.txid, function(tx){
        if (tx) {
          if (tx.vout) { //Added
            console.log('tx.vout: %o', tx.vout); //Added
            module.exports.syncLoop(tx.vout.length, function (loop) {
              var i = loop.iteration();
              if (tx.vout[i].n == input.vout) {
                //module.exports.convert_to_satoshi(parseFloat(tx.vout[i].value), function(amount_sat){
                if (tx.vout[i].scriptPubKey.addresses) {
                  addresses.push({hash: tx.vout[i].scriptPubKey.addresses[0], amount:tx.vout[i].value});
                }
                  loop.break(true);
                  loop.next();
                //});
              } else {
                loop.next();
              }
            }, function(){
              return cb(addresses);
            });
          } else {
            return cb();
          }
        } else {//Added
          return cb();//Added
        }//Added
      });

**Comment by vm06007** [comment] 2018-03-21 22:12
having similar issue

**Comment by voxcon** [comment] 2018-03-22 22:54
@blakey12345 where do i have to implement your code in order to be able to execute the index command correctly?

**Comment by lukepighetti** [comment] 2018-03-25 14:29
Where does this go?

**Comment by lukepighetti** [comment] 2018-03-25 14:33
`/lib/explorer.js Line 341`

**Comment by leegod** [comment] 2018-03-28 09:05
I revised /lib/explorer.js Line 341 with above code, but still get length error.

**Comment by pivxslimjim** [comment] 2018-04-07 14:00
As do i @leegod 
You fix it?

**Comment by olegmitrakhovich** [comment] 2019-08-26 04:04
I used the code provided by blakey, but still getting the same issue also (Cannot read property 'length' of undefined)

**Comment by TheHolyRoger** [comment] 2019-12-25 01:12
Duplicate of https://github.com/iquidus/explorer/issues/56

**Closed by TheHolyRoger** 2019-12-25 01:12 UTC
