### ISSUE TITLE
Heavy setting seemingly ignored

### ISSUE THREAD

**Issue by cruftyoldsysadmin** [iquidus/explorer#133] opened 2018-01-30 12:26 UTC
Enabling "Heavy" in settings.json does not seem to actually set the proper permissions to enable heavy api features:

```
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET /api/tx/ HTTP/1.1

HTTP/1.1 200 OK
X-Powered-By: Express
Date: Tue, 30 Jan 2018 12:26:05 GMT
Connection: keep-alive
Content-Length: 26

This method is restricted.
```

**Comment by TheHolyRoger** [comment] 2019-12-25 01:40
Duplicate of https://github.com/iquidus/explorer/issues/70

**Closed by TheHolyRoger** 2019-12-25 01:40 UTC
