### ISSUE TITLE
how to get chart like that?

### ISSUE THREAD

**Issue by kampungcoin** [iquidus/explorer#152] opened 2018-03-02 16:17 UTC
![image](https://user-images.githubusercontent.com/36219575/36909157-379cd738-1e78-11e8-9ed2-12f47f4454c6.png)

**Comment by popupcoin** [comment] 2019-06-23 14:59
https://www.amcharts.com/download/

this is the chart solution that most of the installs are working with 

`npm install @amcharts/amcharts4
npm install @amcharts/amcharts4-geodata`

**Comment by TheHolyRoger** [comment] 2019-12-25 01:25
This requires historical stat logging. Not something we're looking at for now.

**Comment by TheHolyRoger** [comment] 2019-12-25 01:47
Duplicate of https://github.com/iquidus/explorer/issues/134

**Closed by TheHolyRoger** 2019-12-25 01:47 UTC
Labels: help wanted
