### ISSUE TITLE
Error during Stats Update: { CastError: Cast to number failed for value "NaN" at path "supply"

### ISSUE THREAD

**Issue by TrexcoinTREX** [iquidus/explorer#369] opened 2020-04-12 19:03 UTC
**### Hello Any one Please solve this issue ?**

root@Testcoin_Explorer:/home/explorer# sudo node scripts/sync.js index update
script launched with pid: 2631
Error during Stats Update: { CastError: Cast to number failed for value "NaN" at path "supply"
    at new CastError (/home/explorer/node_modules/mongoose/lib/error/cast.js:29:11)
    at SchemaNumber.cast (/home/explorer/node_modules/mongoose/lib/schema/number.js:315:11)
    at SchemaNumber.SchemaType.applySetters (/home/explorer/node_modules/mongoose/lib/schematype.js:969:12)
    at SchemaNumber.SchemaType._castForQuery (/home/explorer/node_modules/mongoose/lib/schematype.js:1383:15)
    at SchemaNumber.castForQuery (/home/explorer/node_modules/mongoose/lib/schema/number.js:367:14)
    at SchemaNumber.SchemaType.castForQueryWrapper (/home/explorer/node_modules/mongoose/lib/schematype.js:1352:15)
    at castUpdateVal (/home/explorer/node_modules/mongoose/lib/helpers/query/castUpdate.js:463:19)
    at walkUpdatePath (/home/explorer/node_modules/mongoose/lib/helpers/query/castUpdate.js:290:22)
    at castUpdate (/home/explorer/node_modules/mongoose/lib/helpers/query/castUpdate.js:81:18)
    at model.Query._castUpdate (/home/explorer/node_modules/mongoose/lib/query.js:4442:10)
    at castDoc (/home/explorer/node_modules/mongoose/lib/query.js:4470:18)
    at model.Query.Query._findAndModify (/home/explorer/node_modules/mongoose/lib/query.js:3448:22)
    at model.Query.<anonymous> (/home/explorer/node_modules/mongoose/lib/query.js:3001:8)
    at model.Query._wrappedThunk [as _findOneAndUpdate] (/home/explorer/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
    at process.nextTick (/home/explorer/node_modules/kareem/index.js:369:33)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  message: 'Cast to number failed for value "NaN" at path "supply"',
  name: 'CastError',
  stringValue: '"NaN"',
  kind: 'number',
  value: NaN,
  path: 'supply',
  reason: undefined }
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'last' of undefined
    at /home/explorer/lib/database.js:771:31
    at /home/explorer/node_modules/mongoose/lib/model.js:4599:16
    at model.Query.Query._findAndModify (/home/explorer/node_modules/mongoose/lib/query.js:3461:16)
    at model.Query.<anonymous> (/home/explorer/node_modules/mongoose/lib/query.js:3001:8)
    at model.Query._wrappedThunk [as _findOneAndUpdate] (/home/explorer/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
    at process.nextTick (/home/explorer/node_modules/kareem/index.js:369:33)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
root@Testcoin_Explorer:/home/explorer#

![error](https://user-images.githubusercontent.com/63099051/79077298-0f726b80-7d1a-11ea-81a6-4a6351940e9b.png)

**Comment by uaktags** [comment] 2020-04-12 19:08
It won't fix this, but please don't sudo the scripts. There's nothing about them that need root access.

So it looks like either your coin.stats database has NaN written, in which is replace it with 0 and see if that fixes you.

Otherwise, I'm guessing the issue is something is wrong with getting the count from your coind. Try changing to getinfo.

**Comment by TrexcoinTREX** [comment] 2020-04-12 19:14
where i replace 0?? and where i change getinfo ??

**Comment by uaktags** [comment] 2020-04-12 21:24
Inside your settings.json, there's a section for coin supply. Change that
to another setting than coinbase, so like txsetout or getinfo.

**Comment by gogoX1** [comment] 2020-04-15 15:03
Hello i have the same Problem, have you already found a solution


root@***********~/explorer# sudo node scripts/sync.js index update
script launched with pid: 17386
Error during Stats Update: { CastError: Cast to number failed for value "NaN" at path "supply"
    at new CastError (/root/explorer/node_modules/mongoose/lib/error/cast.js:29:11)
    at SchemaNumber.cast (/root/explorer/node_modules/mongoose/lib/schema/number.js:315:11)
    at SchemaNumber.SchemaType.applySetters (/root/explorer/node_modules/mongoose/lib/schematype.js:969:12)
    at SchemaNumber.SchemaType._castForQuery (/root/explorer/node_modules/mongoose/lib/schematype.js:1383:15)
    at SchemaNumber.castForQuery (/root/explorer/node_modules/mongoose/lib/schema/number.js:367:14)
    at SchemaNumber.SchemaType.castForQueryWrapper (/root/explorer/node_modules/mongoose/lib/schematype.js:1352:15)
    at castUpdateVal (/root/explorer/node_modules/mongoose/lib/helpers/query/castUpdate.js:463:19)
    at walkUpdatePath (/root/explorer/node_modules/mongoose/lib/helpers/query/castUpdate.js:290:22)
    at castUpdate (/root/explorer/node_modules/mongoose/lib/helpers/query/castUpdate.js:81:18)
    at model.Query._castUpdate (/root/explorer/node_modules/mongoose/lib/query.js:4442:10)
    at castDoc (/root/explorer/node_modules/mongoose/lib/query.js:4470:18)
    at model.Query.Query._findAndModify (/root/explorer/node_modules/mongoose/lib/query.js:3448:22)
    at model.Query.<anonymous> (/root/explorer/node_modules/mongoose/lib/query.js:3001:8)
    at model.Query._wrappedThunk [as _findOneAndUpdate] (/root/explorer/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
    at process.nextTick (/root/explorer/node_modules/kareem/index.js:369:33)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  message: 'Cast to number failed for value "NaN" at path "supply"',
  name: 'CastError',
  stringValue: '"NaN"',
  kind: 'number',
  value: NaN,
  path: 'supply',
  reason: undefined }
events.js:174
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'last' of undefined
    at /root/explorer/lib/database.js:771:31
    at /root/explorer/node_modules/mongoose/lib/model.js:4599:16
    at model.Query.Query._findAndModify (/root/explorer/node_modules/mongoose/lib/query.js:3461:16)
    at model.Query.<anonymous> (/root/explorer/node_modules/mongoose/lib/query.js:3001:8)
    at model.Query._wrappedThunk [as _findOneAndUpdate] (/root/explorer/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
    at process.nextTick (/root/explorer/node_modules/kareem/index.js:369:33)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Emitted 'error' event at:
    at /root/explorer/node_modules/mongoose/lib/model.js:4601:13
    at model.Query.Query._findAndModify (/root/explorer/node_modules/mongoose/lib/query.js:3461:16)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by gogoX1** [comment] 2020-04-15 16:56
https://github.com/iquidus/explorer/issues/350#issuecomment-589806514 works for me thx

**Closed** 2020-07-16 21:48 UTC
