### ISSUE TITLE
Cannot read property 0 of undefined during index update

### ISSUE THREAD

**Issue by maxya** [iquidus/explorer#78] opened 2017-06-13 16:39 UTC
Hello, 
I'm getting following error `Cannot read property 0 of undefined' during initial sync/update.`
Coin - BTC
```javascript
maxim@coin:~/explorer$ node  --stack-size=65000 scripts/sync.js index update
script launched with pid: 105737
/home/ibob/explorer/lib/explorer.js:290
        module.exports.is_unique(arr_vout, vout[i].scriptPubKey.addresses[0], function(unique, index) {
                                                                         ^
TypeError: Cannot read property '0' of undefined
    at module.exports.syncLoop.arr_vout.(anonymous function).amount (/home/maxim/explorer/lib/explorer.js:290:74)
    at Object.next (/home/maxim/explorer/lib/explorer.js:189:18)
    at /home/maxim/explorer/lib/explorer.js:295:20
    at Object.convert_to_satoshi (/home/maxim/explorer/lib/explorer.js:25:12)
    at /home/maxim/explorer/lib/explorer.js:293:28
    at /home/maxim/explorer/lib/explorer.js:263:14
    at Object.next (/home/maxim/explorer/lib/explorer.js:194:24)
    at Object.syncLoop (/home/maxim/explorer/lib/explorer.js:205:10)
    at Object.is_unique (/home/maxim/explorer/lib/explorer.js:252:20)
    at module.exports.syncLoop.arr_vout.(anonymous function).amount (/home/maxim/explorer/lib/explorer.js:290:24)
    at Object.next (/home/maxim/explorer/lib/explorer.js:189:18)
    at Object.syncLoop (/home/maxim/explorer/lib/explorer.js:205:10)
    at Object.prepare_vout (/home/maxim/explorer/lib/explorer.js:284:20)
    at /home/maxim/explorer/lib/database.js:141:17
    at /home/maxim/explorer/lib/explorer.js:392:14
    at Object.next (/home/maxim/explorer/lib/explorer.js:194:24)

```
Any advice? 
Thank you

**Comment by parisnakitakejser** [comment] 2018-02-14 19:54
i have the same issue, when i try to run it, hope the bug will be fixed/found

**Comment by rbtgit** [comment] 2018-02-24 16:45
I've had this issue and fixed it by changing the following line in explorer.js:
`if (vout[i].scriptPubKey.type != 'nonstandard' && vout[i].scriptPubKey.type != 'nulldata') { `
to
`if (vout[i].scriptPubKey.type != 'nonstandard' && vout[i].scriptPubKey.type != 'nulldata' && vout[i].scriptPubKey.hasOwnProperty("addresses")) { `

**Comment by Rav3nPL** [comment] 2018-03-06 13:25
I get similar ```"TypeError: Cannot read property '0' of undefined"```
```
script launched with pid: 20777
/home/rav3n/explorer/lib/explorer.js:290
        module.exports.is_unique(arr_vout, vout[i].scriptPubKey.addresses[0], function(unique, index) {
                                                                         ^

TypeError: Cannot read property '0' of undefined
    at module.exports.syncLoop.arr_vout.(anonymous function).amount (/home/rav3n/explorer/lib/explorer.js:290:74)
    at Object.next (/home/rav3n/explorer/lib/explorer.js:189:18)
    at Object.syncLoop (/home/rav3n/explorer/lib/explorer.js:205:10)
    at Object.prepare_vout (/home/rav3n/explorer/lib/explorer.js:284:20)
    at /home/rav3n/explorer/lib/database.js:141:17
    at /home/rav3n/explorer/lib/explorer.js:392:14
    at Object.next (/home/rav3n/explorer/lib/explorer.js:194:24)
    at /home/rav3n/explorer/lib/explorer.js:378:22
    at Object.convert_to_satoshi (/home/rav3n/explorer/lib/explorer.js:25:12)
    at /home/rav3n/explorer/lib/explorer.js:376:30
    at /home/rav3n/explorer/lib/explorer.js:263:14
    at Object.next (/home/rav3n/explorer/lib/explorer.js:194:24)
    at Object.syncLoop (/home/rav3n/explorer/lib/explorer.js:205:10)
    at Object.is_unique (/home/rav3n/explorer/lib/explorer.js:252:20)
    at /home/rav3n/explorer/lib/explorer.js:374:26
    at /home/rav3n/explorer/lib/explorer.js:358:20
```
It is on altcoin network that is using native segwit addresses...

**Comment by Rav3nPL** [comment] 2018-03-06 13:35
@rbtgit your change is suppresing error, but explorer not showing up native segwit address part at all.
I think it needs more changes :(

**Comment by smai2018** [comment] 2018-06-22 18:19
The same issue here:

/root/explorer/lib/explorer.js:290
        module.exports.is_unique(arr_vout, vout[i].scriptPubKey.addresses[0], function(unique, index) {
                                                                         ^

TypeError: Cannot read property '0' of undefined
    at module.exports.syncLoop.arr_vout.(anonymous function).amount (/root/explorer/lib/explorer.js:290:74)
    at Object.loop.next (/root/explorer/lib/explorer.js:189:18)
    at Object.module.exports.syncLoop (/root/explorer/lib/explorer.js:205:10)
    at Object.module.exports.prepare_vout (/root/explorer/lib/explorer.js:284:20)
    at /root/explorer/lib/database.js:141:17
    at /root/explorer/lib/explorer.js:392:14
    at Object.loop.next (/root/explorer/lib/explorer.js:194:24)
    at /root/explorer/lib/explorer.js:378:22
    at Object.module.exports.convert_to_satoshi (/root/explorer/lib/explorer.js:25:12)
    at /root/explorer/lib/explorer.js:376:30
    at /root/explorer/lib/explorer.js:263:14
    at Object.loop.next (/root/explorer/lib/explorer.js:194:24)
    at Object.module.exports.syncLoop (/root/explorer/lib/explorer.js:205:10)
    at Object.module.exports.is_unique (/root/explorer/lib/explorer.js:252:20)
    at /root/explorer/lib/explorer.js:374:26
    at /root/explorer/lib/explorer.js:358:20

**Comment by smai2018** [comment] 2018-06-22 19:33
I think I found the bug: 

![image](https://user-images.githubusercontent.com/37613028/41795643-be85a0de-7663-11e8-8afe-4a9b969bed6c.png)

It shows exactly the exeption scriptPubKey.addresses[0] - TypeError: Cannot read property '0' of undefined

**Comment by smai2018** [comment] 2018-06-22 20:08
rbtgit workaround works! Thanks!

**Comment by TheHolyRoger** [comment] 2019-12-25 01:10
Duplicate of https://github.com/iquidus/explorer/issues/56

**Closed by TheHolyRoger** 2019-12-25 01:10 UTC

**Comment by MatrixR00T** [comment] 2020-08-31 08:09
> if (vout[i].scriptPubKey.type != 'nonstandard' && vout[i].scriptPubKey.type != 'nulldata' && vout[i].scriptPubKey.hasOwnProperty("addresses")) {


WORKS!
