### ISSUE TITLE
How fix this issue? TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by mraksoll4** [iquidus/explorer#348] opened 2020-02-10 22:18 UTC
```
script launched with pid: 2340
/root/explorer/lib/explorer.js:582
    module.exports.syncLoop(tx.vin.length, function (loop)

TypeError: Cannot read property 'length' of undefined
    at Object.prepare_vin (/root/explorer/lib/explorer.js:582:36)
    at /root/explorer/lib/database.js:128:11
    at Request._callback (/root/explorer/lib/explorer.js:212:16)
    at Request.self.callback (/root/explorer/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/root/explorer/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/root/explorer/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

i use node 8.17.0
mongo 4.2

when i use 

node scripts/sync.js index reindex its start work
node scripts/sync.js index check to work 
When i try  node scripts/sync.js index update ( its give me this error )

I try this fix
https://github.com/MotorMan/explorer/commit/97cf3f225c57c36ffa00d3b76ed74a688da2eae5
 but notting 

wallet synced with txindex=1 

1.7.2 ver work normal

**Comment by mraksoll4** [comment] 2020-02-10 23:28
`root@pool:~/explorer# node scripts/sync.js index update
script launched with pid: 4237
Error during Stats Update: { CastError: Cast to number failed for value "NaN" at path "supply"
    at new CastError (/root/explorer/node_modules/mongoose/lib/error/cast.js:29:11)
    at SchemaNumber.cast (/root/explorer/node_modules/mongoose/lib/schema/number.js:315:11)
    at SchemaNumber.SchemaType.applySetters (/root/explorer/node_modules/mongoose/lib/schematype.js:969:12)
    at SchemaNumber.SchemaType._castForQuery (/root/explorer/node_modules/mongoose/lib/schematype.js:1383:15)
    at SchemaNumber.castForQuery (/root/explorer/node_modules/mongoose/lib/schema/number.js:367:14)
    at SchemaNumber.SchemaType.castForQueryWrapper (/root/explorer/node_modules/mongoose/lib/schematype.js:1352:15)
    at castUpdateVal (/root/explorer/node_modules/mongoose/lib/helpers/query/castUpdate.js:463:19)
    at walkUpdatePath (/root/explorer/node_modules/mongoose/lib/helpers/query/castUpdate.js:290:22)
    at castUpdate (/root/explorer/node_modules/mongoose/lib/helpers/query/castUpdate.js:81:18)
    at model.Query._castUpdate (/root/explorer/node_modules/mongoose/lib/query.js:4442:10)
    at castDoc (/root/explorer/node_modules/mongoose/lib/query.js:4470:18)
    at model.Query.Query._findAndModify (/root/explorer/node_modules/mongoose/lib/query.js:3448:22)
    at model.Query.<anonymous> (/root/explorer/node_modules/mongoose/lib/query.js:3001:8)
    at model.Query._wrappedThunk [as _findOneAndUpdate] (/root/explorer/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
    at process.nextTick (/root/explorer/node_modules/kareem/index.js:369:33)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  message: 'Cast to number failed for value "NaN" at path "supply"',
  name: 'CastError',
  stringValue: '"NaN"',
  kind: 'number',
  value: NaN,
  path: 'supply',
  reason: undefined }
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'last' of undefined
    at /root/explorer/lib/database.js:757:31
    at /root/explorer/node_modules/mongoose/lib/model.js:4599:16
    at model.Query.Query._findAndModify (/root/explorer/node_modules/mongoose/lib/query.js:3461:16)
    at model.Query.<anonymous> (/root/explorer/node_modules/mongoose/lib/query.js:3001:8)
    at model.Query._wrappedThunk [as _findOneAndUpdate] (/root/explorer/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
    at process.nextTick (/root/explorer/node_modules/kareem/index.js:369:33)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
`

**Comment by uaktags** [comment] 2020-02-11 00:37
That fix is for a different issue. Your issue is that there are no vins in that transaction, which is why it says it can't read "length" property of that transactions vins.
https://github.com/iquidus/explorer/blob/56e37523263bd81d57dfc420416c1b0426b875a7/lib/explorer.js#L582
Find out what the last block is that's been recorded, then manually get the transactions of the next block (the one that's failing), and then check to see if there's any transactions that have an issue.

You can also, more easily, just console.log out what "tx" is and then you can check those results against what the coind shows.

**Comment by mraksoll4** [comment] 2020-02-11 01:37
1.7.2 work perfect , 1.7.3 give this issue and only at update 

reindex and check work with no errors.

it's fails from 0 block.

**Comment by uaktags** [comment] 2020-02-11 03:39
Welp, then there's nothing I can do and can just close this issue...you've removed the ability to troubleshoot.

Next time though, try something a bit more useful for issue diagnostics:
the error was given to you saying what it was, and my explanation explains why its erroring (using the information from the error message). I even provided a VERY USEFUL step to see what's going on: 

> just console.log out what "tx" is and then you can check those results against what the coind shows.

That part, should have given you the tx as a json. That json should, in theory if its pulling a transaction or if something else is coming along. Is the wallet settings correct, is the results returning correctly,etc.

Please note that if I don't know what coin it is, and can't reproduce the issue, then I can't help with anything. At present, the error message explains the issue and it relates to what was provided by the coind (whatever coin it may have been).

**Closed by uaktags** 2020-02-11 03:39 UTC

**Comment by lubhub612** [comment] 2020-02-14 08:31
![image](https://user-images.githubusercontent.com/45089340/74514396-764df100-4f32-11ea-9e2c-7fa347d53f7b.png)

**Comment by lubhub612** [comment] 2020-02-14 08:31
any suggestion @uaktags
