### ISSUE TITLE
Cant sync ZCash Testnet

### ISSUE THREAD

**Issue by reactionstudio** [iquidus/explorer#285] opened 2019-05-21 01:39 UTC
When trying to sync the zcash testnet for the first time on a fresh install i get the following error:

```
......
5647: 4d6c185bd244c061fc1ede9b9023818498f05eb509ab59acd6d1f423aac600e3
5648: 0c38cbd995c573e6b52d95a7a19d68ba77c9470d239ed37a0e0f2f466d9b53f8
5649: 864b9ba2c9c4d6d489df78e47ff8a6b24de668a2679f83a1f54ad4c81e4b2b69
/home/user/zcash_testnet/lib/explorer.js:290
        module.exports.is_unique(arr_vout, vout[i].scriptPubKey.addresses[0], function(unique, index) {
                                                                         ^

TypeError: Cannot read property '0' of undefined
    at /home/user/zcash_testnet/lib/explorer.js:290:74
    at Object.next (/home/user/zcash_testnet/lib/explorer.js:189:18)
    at Object.syncLoop (/home/user/zcash_testnet/lib/explorer.js:205:10)
    at Object.prepare_vout (/home/user/zcash_testnet/lib/explorer.js:284:20)
    at /home/user/zcash_testnet/lib/database.js:141:17
    at /home/user/zcash_testnet/lib/explorer.js:395:14
    at Object.next (/home/user/zcash_testnet/lib/explorer.js:194:24)
    at /home/user/zcash_testnet/lib/explorer.js:381:22
    at Object.convert_to_satoshi (/home/user/zcash_testnet/lib/explorer.js:25:12)
    at /home/user/zcash_testnet/lib/explorer.js:379:30
    at /home/user/zcash_testnet/lib/explorer.js:263:14
    at Object.next (/home/user/zcash_testnet/lib/explorer.js:194:24)
    at Object.syncLoop (/home/user/zcash_testnet/lib/explorer.js:205:10)
    at Object.is_unique (/home/user/zcash_testnet/lib/explorer.js:252:20)
    at /home/user/zcash_testnet/lib/explorer.js:377:26
    at /home/user/zcash_testnet/lib/explorer.js:342:16

```
I'm running on ubuntu server 18.04.

**Comment by uaktags** [comment] 2019-05-26 22:10
Thanks for providing the info on the coin and the network. Could you try console.log'ing out what ```vout[i].scriptPubKey.addresses```. My guess is there's no check/balance to verify that this is infact an array of addresses. You could also do a typeof against it.

**Comment by TheHolyRoger** [comment] 2019-12-25 01:14
Duplicate of https://github.com/iquidus/explorer/issues/56

**Closed by TheHolyRoger** 2019-12-25 01:14 UTC
