### ISSUE TITLE
script launched with pid: 714  TypeError: Cannot read property 'length' of undefined     at /www/wwwroot/explorer4/lib/database.js:642:36     at Request._callback (/www/wwwroot/explorer4/lib/explorer.js:107:14)     at Request.self.callback (/www/wwwroot/explorer4/node_modules/request/request.js:187:22)     at Request.emit (events.js:98:17)     at Request.<anonymous> (/www/wwwroot/explorer4/node_modules/request/request.js:1044:10)     at Request.emit (events.js:95:17)     at IncomingMessage.<anonymous> (/www/wwwroot/explorer4/node_modules/request/request.js:965:12)     at IncomingMessage.emit (events.js:117:20)     at _stream_readable.js:943:16     at process._tickCallback (node.js:419:13)

### ISSUE THREAD

**Issue by zhq1** [iquidus/explorer#110] opened 2017-11-09 15:08 UTC
script launched with pid: 714

TypeError: Cannot read property 'length' of undefined
    at /www/wwwroot/explorer4/lib/database.js:642:36
    at Request._callback (/www/wwwroot/explorer4/lib/explorer.js:107:14)
    at Request.self.callback (/www/wwwroot/explorer4/node_modules/request/request.js:187:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/www/wwwroot/explorer4/node_modules/request/request.js:1044:10)
    at Request.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/www/wwwroot/explorer4/node_modules/request/request.js:965:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)

**Comment by TheHolyRoger** [comment] 2019-12-25 01:11
Duplicate of https://github.com/iquidus/explorer/issues/56

**Closed by TheHolyRoger** 2019-12-25 01:11 UTC
