### ISSUE TITLE
Sync data crashed in the middle in Kurrent coin

### ISSUE THREAD

**Issue by kurrentproject** [iquidus/explorer#63] opened 2016-12-30 02:59 UTC
I set up an iquidus explorer for Kurrent (https://bitcointalk.org/index.php?topic=1691086.0), a zerocoin/X11 coin. When I sync data with sync.js (index update), everything goes on well until block 1257, where there's a vout[1], and it crashes:

1256: b2baf0dc884dcee7f56faae7e0b69a5db9d08165bfb5bfbe8709c5008df85df5
vout:0:bd70165c6ef524ba7cfff71403e72c1df285b9ab0c33f49a9e176429bcf31a43
1257: bd70165c6ef524ba7cfff71403e72c1df285b9ab0c33f49a9e176429bcf31a43
vout:0:887aded62f59bb442284259bc98283013be8c55037f120424ce9524f61f2616f
vout:1:887aded62f59bb442284259bc98283013be8c55037f120424ce9524f61f2616f

TypeError: Cannot read property '0' of undefined
    at module.exports.syncLoop.arr_vout.(anonymous function).amount (/var/www/ht
ml/iquidus-explorer/lib/explorer.js:291:74)
    at Object.loop.next (/var/www/html/iquidus-explorer/lib/explorer.js:189:18)
    at /var/www/html/iquidus-explorer/lib/explorer.js:296:20
    at Object.module.exports.convert_to_satoshi (/var/www/html/iquidus-explorer/
lib/explorer.js:25:12)
    at /var/www/html/iquidus-explorer/lib/explorer.js:294:28
    at /var/www/html/iquidus-explorer/lib/explorer.js:263:14
    at Object.loop.next (/var/www/html/iquidus-explorer/lib/explorer.js:194:24)
    at Object.module.exports.syncLoop (/var/www/html/iquidus-explorer/lib/explor
er.js:205:10)
    at Object.module.exports.is_unique (/var/www/html/iquidus-explorer/lib/explo
rer.js:252:20)
    at module.exports.syncLoop.arr_vout.(anonymous function).amount (/var/www/ht
ml/iquidus-explorer/lib/explorer.js:291:24)
    at Object.loop.next (/var/www/html/iquidus-explorer/lib/explorer.js:189:18)
    at Object.module.exports.syncLoop (/var/www/html/iquidus-explorer/lib/explor
er.js:205:10)
    at Object.module.exports.prepare_vout (/var/www/html/iquidus-explorer/lib/ex
plorer.js:284:20)
    at /var/www/html/iquidus-explorer/lib/database.js:141:17
    at /var/www/html/iquidus-explorer/lib/explorer.js:393:14
    at Object.loop.next (/var/www/html/iquidus-explorer/lib/explorer.js:194:24)

I tried to sync only with vout[0], but still there are similar errors after a few more blocks. Any suggestions? Thanks.

**Comment by kurrentproject** [comment] 2017-01-07 22:53
this is where the Kurrent is minted into zerocoin, corresponding to a temporary destruction of the coin, where the explorer not working. Hope dev has a simple way to get around it.

**Comment by iquidus** [comment] 2017-01-16 10:09
This is something I will need to look into further.

**Comment by zoincoin** [comment] 2017-03-18 10:18
I have the same problem on Zoin coin. The script is locked on the first zerocoin transaction

**Comment by rbtgit** [comment] 2018-02-24 16:46
I've had this issue and fixed it by changing the following line in explorer.js:
`if (vout[i].scriptPubKey.type != 'nonstandard' && vout[i].scriptPubKey.type != 'nulldata') { `
to
`if (vout[i].scriptPubKey.type != 'nonstandard' && vout[i].scriptPubKey.type != 'nulldata' && vout[i].scriptPubKey.hasOwnProperty("addresses")) { `

**Comment by TheHolyRoger** [comment] 2019-12-25 01:37
Duplicate of https://github.com/iquidus/explorer/issues/56

**Closed by TheHolyRoger** 2019-12-25 01:37 UTC
