### ISSUE TITLE
Cant sync Dash Testnet

### ISSUE THREAD

**Issue by reactionstudio** [iquidus/explorer#286] opened 2019-05-21 02:12 UTC
When syncing for the first time on the Dash testnet i'm getting the following error:

```
....
6998: 503b5e1a0000bda82edec2cb918b79a31383d4c20d7ad409dae9c68f65439d87
6999: 9c7a22d66c5a61aa9d265fb274412e76e3140334cefa9575ae24d91573264dff
7000: 61bc32c39a523a7705eaa52724b80d52741025547d6562d9fc588617790a06ce
/home/user/dash_testnet/lib/explorer.js:310
      if (vout[0].scriptPubKey.type == 'nonstandard') {
                  ^

TypeError: Cannot read property 'scriptPubKey' of undefined
    at /home/user/dash_testnet/lib/explorer.js:310:19
    at Object.next (/home/user/dash_testnet/lib/explorer.js:194:24)
    at Object.syncLoop (/home/user/dash_testnet/lib/explorer.js:205:10)
    at Object.prepare_vout (/home/user/dash_testnet/lib/explorer.js:284:20)
    at /home/user/dash_testnet/lib/database.js:141:17
    at /home/user/dash_testnet/lib/explorer.js:392:14
    at Object.next (/home/user/dash_testnet/lib/explorer.js:194:24)
    at Object.syncLoop (/home/user/dash_testnet/lib/explorer.js:205:10)
    at Object.prepare_vin (/home/user/dash_testnet/lib/explorer.js:369:20)
    at /home/user/dash_testnet/lib/database.js:140:15
    at Request._callback (/home/user/dash_testnet/lib/explorer.js:107:14)
    at Request.self.callback (/home/user/dash_testnet/node_modules/request/request.js:187:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/user/dash_testnet/node_modules/request/request.js:1044:10)
    at emitOne (events.js:116:13)
```

I'm running on ubuntu 18.04

**Comment by uaktags** [comment] 2019-05-26 22:11
could you try to capture what vout[0] is providing you?

**Comment by walletbuilders** [comment] 2019-07-31 06:59
The same error message occurs when used with coins based on Dash.

Command executed: **sudo node scripts/sync.js index update**
Error message:

10: ad41cb231ba1c41066555c71e48900fc0df476e42974dfe341265c652ed40e5c
/root/explorer/lib/explorer.js:310
      if (vout[0].scriptPubKey.type == 'nonstandard') {
                 ^

TypeError: Cannot read property 'scriptPubKey' of undefined
    at /root/explorer/lib/explorer.js:310:18
    at Object.loop.next (/root/explorer/lib/explorer.js:194:24)
    at Object.module.exports.syncLoop (/root/explorer/lib/explorer.js:205:10)
    at Object.module.exports.prepare_vout (/root/explorer/lib/explorer.js:284:20)
    at /root/explorer/lib/database.js:141:17
    at /root/explorer/lib/explorer.js:392:14
    at Object.loop.next (/root/explorer/lib/explorer.js:194:24)
    at Object.module.exports.syncLoop (/root/explorer/lib/explorer.js:205:10)
    at Object.module.exports.prepare_vin (/root/explorer/lib/explorer.js:369:20)
    at /root/explorer/lib/database.js:140:15
    at Request._callback (/root/explorer/lib/explorer.js:107:14)
    at Request.self.callback (/root/explorer/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/root/explorer/node_modules/request/request.js:1044:10)
    at emitOne (events.js:77:13)

Command: **getblock 00000062dd01170ea0b91e3bb87f76e4bb2fcd9784181fe2280714316ea1e638**

Output: {
  "hash": "00000062dd01170ea0b91e3bb87f76e4bb2fcd9784181fe2280714316ea1e638",
  "confirmations": 3518,
  "size": 560,
  "height": 10,
  "version": 536870943,
  "versionHex": "2000001f",
  "merkleroot": "18c7453054908d3aa67afce771d70263598b93d7472c96310cf6b75f3b434fda",
  "tx": [
    "ad41cb231ba1c41066555c71e48900fc0df476e42974dfe341265c652ed40e5c", 
    "97f6c697c4da02da7970290020e65da050f85293802ad93334ca038d4c3d8cab"
  ],
  "cbTx": {
    "version": 1,
    "height": 10,
    "merkleRootMNList": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  "time": 1563793156,
  "mediantime": 1563792793,
  "nonce": 48408,
  "bits": "1e0fffff",
  "difficulty": 0.0002441371325370145,
  "chainwork": "0000000000000000000000000000000000000000000000000000000000b0001a",
  "previousblockhash": "00000fc3474df9731297eb0d324e6bd9d9def55c9cfe1e14f11b455ad01e3018",
  "nextblockhash": "000006ce58d88deeff4bb1b7e2b613fcd28a3eae910a846ea659eb1d210459b6",
  "chainlock": false
}

Command: **getrawtransaction ad41cb231ba1c41066555c71e48900fc0df476e42974dfe341265c652ed40e5c 1**

Output: 
{
  "hex": "03000500010000000000000000000000000000000000000000000000000000000000000000ffffffff035a0106ffffffff010067047600000000232103ca7fbcc0e65aa35bfeb740b1742b89cf877368fda46206ffdf3030573991c99fac000000002601000a0000000000000000000000000000000000000000000000000000000000000000000000",
  "txid": "ad41cb231ba1c41066555c71e48900fc0df476e42974dfe341265c652ed40e5c",
  "size": 137,
  "version": 3,
  "type": 5,
  "locktime": 0,
  "vin": [
    {
      "coinbase": "5a0106",
      "sequence": 4294967295
    }
  ],
  "vout": [
    {
      "value": 19.80000000,
      "valueSat": 1980000000,
      "n": 0,
      "scriptPubKey": {
        "asm": "03ca7fbcc0e65aa35bfeb740b1742b89cf877368fda46206ffdf3030573991c99f OP_CHECKSIG",
        "hex": "2103ca7fbcc0e65aa35bfeb740b1742b89cf877368fda46206ffdf3030573991c99fac",
        "reqSigs": 1,
        "type": "pubkey",
        "addresses": [
          "1MMYg9ScNvYMy7s1mRdyahLTV3HHJvCBYy"
        ]
      }
    }
  ],
  "extraPayloadSize": 38,
  "extraPayload": "01000a0000000000000000000000000000000000000000000000000000000000000000000000",
  "cbTx": {
    "version": 1,
    "height": 10,
    "merkleRootMNList": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  "blockhash": "00000062dd01170ea0b91e3bb87f76e4bb2fcd9784181fe2280714316ea1e638",
  "height": 10,
  "confirmations": 3519,
  "time": 1563793156,
  "blocktime": 1563793156,
  "instantlock": false,
  "instantlock_internal": false,
  "chainlock": false
}

Command: **getrawtransaction 97f6c697c4da02da7970290020e65da050f85293802ad93334ca038d4c3d8cab 1**

Output: 
getrawtransaction 97f6c697c4da02da7970290020e65da050f85293802ad93334ca038d4c3d8cab 1
{
  "hex": "03000600000000000000fd490101000a000000010001a814e57535f9c6c32e6f7ced23fec4bbc5c78a465a29fb69381776c3760a0000320000000000000032000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "txid": "97f6c697c4da02da7970290020e65da050f85293802ad93334ca038d4c3d8cab",
  "size": 342,
  "version": 3,
  "type": 6,
  "locktime": 0,
  "vin": [
  ],
  "vout": [
  ],
  "extraPayloadSize": 329,
  "extraPayload": "01000a000000010001a814e57535f9c6c32e6f7ced23fec4bbc5c78a465a29fb69381776c3760a0000320000000000000032000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "qcTx": {
    "version": 1,
    "height": 10,
    "commitment": {
      "version": 1,
      "llmqType": 1,
      "quorumHash": "00000a76c376173869fb295a468ac7c5bbc4fe23ed7c6f2ec3c6f93575e514a8",
      "signersCount": 0,
      "validMembersCount": 0,
      "quorumPublicKey": "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    }
  },
  "blockhash": "00000062dd01170ea0b91e3bb87f76e4bb2fcd9784181fe2280714316ea1e638",
  "height": 10,
  "confirmations": 3521,
  "time": 1563793156,
  "blocktime": 1563793156,
  "instantlock": false,
  "instantlock_internal": false,
  "chainlock": false
}

**Comment by BlockGardener** [comment] 2019-07-31 07:01
The same error message occurs when used with coins based on Dash.

Command executed: **sudo node scripts/sync.js index update**
Error message:

10: ad41cb231ba1c41066555c71e48900fc0df476e42974dfe341265c652ed40e5c
/root/explorer/lib/explorer.js:310
      if (vout[0].scriptPubKey.type == 'nonstandard') {
                 ^

TypeError: Cannot read property 'scriptPubKey' of undefined
    at /root/explorer/lib/explorer.js:310:18
    at Object.loop.next (/root/explorer/lib/explorer.js:194:24)
    at Object.module.exports.syncLoop (/root/explorer/lib/explorer.js:205:10)
    at Object.module.exports.prepare_vout (/root/explorer/lib/explorer.js:284:20)
    at /root/explorer/lib/database.js:141:17
    at /root/explorer/lib/explorer.js:392:14
    at Object.loop.next (/root/explorer/lib/explorer.js:194:24)
    at Object.module.exports.syncLoop (/root/explorer/lib/explorer.js:205:10)
    at Object.module.exports.prepare_vin (/root/explorer/lib/explorer.js:369:20)
    at /root/explorer/lib/database.js:140:15
    at Request._callback (/root/explorer/lib/explorer.js:107:14)
    at Request.self.callback (/root/explorer/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/root/explorer/node_modules/request/request.js:1044:10)
    at emitOne (events.js:77:13)

Command: **getblock 00000062dd01170ea0b91e3bb87f76e4bb2fcd9784181fe2280714316ea1e638**

Output: {
  "hash": "00000062dd01170ea0b91e3bb87f76e4bb2fcd9784181fe2280714316ea1e638",
  "confirmations": 3518,
  "size": 560,
  "height": 10,
  "version": 536870943,
  "versionHex": "2000001f",
  "merkleroot": "18c7453054908d3aa67afce771d70263598b93d7472c96310cf6b75f3b434fda",
  "tx": [
    "ad41cb231ba1c41066555c71e48900fc0df476e42974dfe341265c652ed40e5c", 
    "97f6c697c4da02da7970290020e65da050f85293802ad93334ca038d4c3d8cab"
  ],
  "cbTx": {
    "version": 1,
    "height": 10,
    "merkleRootMNList": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  "time": 1563793156,
  "mediantime": 1563792793,
  "nonce": 48408,
  "bits": "1e0fffff",
  "difficulty": 0.0002441371325370145,
  "chainwork": "0000000000000000000000000000000000000000000000000000000000b0001a",
  "previousblockhash": "00000fc3474df9731297eb0d324e6bd9d9def55c9cfe1e14f11b455ad01e3018",
  "nextblockhash": "000006ce58d88deeff4bb1b7e2b613fcd28a3eae910a846ea659eb1d210459b6",
  "chainlock": false
}

Command: **getrawtransaction ad41cb231ba1c41066555c71e48900fc0df476e42974dfe341265c652ed40e5c 1**

Output: 
{
  "hex": "03000500010000000000000000000000000000000000000000000000000000000000000000ffffffff035a0106ffffffff010067047600000000232103ca7fbcc0e65aa35bfeb740b1742b89cf877368fda46206ffdf3030573991c99fac000000002601000a0000000000000000000000000000000000000000000000000000000000000000000000",
  "txid": "ad41cb231ba1c41066555c71e48900fc0df476e42974dfe341265c652ed40e5c",
  "size": 137,
  "version": 3,
  "type": 5,
  "locktime": 0,
  "vin": [
    {
      "coinbase": "5a0106",
      "sequence": 4294967295
    }
  ],
  "vout": [
    {
      "value": 19.80000000,
      "valueSat": 1980000000,
      "n": 0,
      "scriptPubKey": {
        "asm": "03ca7fbcc0e65aa35bfeb740b1742b89cf877368fda46206ffdf3030573991c99f OP_CHECKSIG",
        "hex": "2103ca7fbcc0e65aa35bfeb740b1742b89cf877368fda46206ffdf3030573991c99fac",
        "reqSigs": 1,
        "type": "pubkey",
        "addresses": [
          "1MMYg9ScNvYMy7s1mRdyahLTV3HHJvCBYy"
        ]
      }
    }
  ],
  "extraPayloadSize": 38,
  "extraPayload": "01000a0000000000000000000000000000000000000000000000000000000000000000000000",
  "cbTx": {
    "version": 1,
    "height": 10,
    "merkleRootMNList": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  "blockhash": "00000062dd01170ea0b91e3bb87f76e4bb2fcd9784181fe2280714316ea1e638",
  "height": 10,
  "confirmations": 3519,
  "time": 1563793156,
  "blocktime": 1563793156,
  "instantlock": false,
  "instantlock_internal": false,
  "chainlock": false
}

Command: **getrawtransaction 97f6c697c4da02da7970290020e65da050f85293802ad93334ca038d4c3d8cab 1**

Output: 
getrawtransaction 97f6c697c4da02da7970290020e65da050f85293802ad93334ca038d4c3d8cab 1
{
  "hex": "03000600000000000000fd490101000a000000010001a814e57535f9c6c32e6f7ced23fec4bbc5c78a465a29fb69381776c3760a0000320000000000000032000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "txid": "97f6c697c4da02da7970290020e65da050f85293802ad93334ca038d4c3d8cab",
  "size": 342,
  "version": 3,
  "type": 6,
  "locktime": 0,
  "vin": [
  ],
  "vout": [
  ],
  "extraPayloadSize": 329,
  "extraPayload": "01000a000000010001a814e57535f9c6c32e6f7ced23fec4bbc5c78a465a29fb69381776c3760a0000320000000000000032000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "qcTx": {
    "version": 1,
    "height": 10,
    "commitment": {
      "version": 1,
      "llmqType": 1,
      "quorumHash": "00000a76c376173869fb295a468ac7c5bbc4fe23ed7c6f2ec3c6f93575e514a8",
      "signersCount": 0,
      "validMembersCount": 0,
      "quorumPublicKey": "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    }
  },
  "blockhash": "00000062dd01170ea0b91e3bb87f76e4bb2fcd9784181fe2280714316ea1e638",
  "height": 10,
  "confirmations": 3521,
  "time": 1563793156,
  "blocktime": 1563793156,
  "instantlock": false,
  "instantlock_internal": false,
  "chainlock": false
}

**Comment by BlockGardener** [comment] 2019-09-03 09:56
I fixed the issue by installing a patch.

Run the following commands from inside the explorer folder to install the patch.

wget https://raw.githubusercontent.com/walletbuilders/iquidus-x11-patch/master/iquidus_x11_patch.diff
patch -p1 < iquidus_x11_patch.diff

The content of the patch is visible on the following page:
https://github.com/walletbuilders/iquidus-x11-patch/blob/master/iquidus_x11_patch.diff

**Comment by TheHolyRoger** [comment] 2019-12-25 01:14
Duplicate of https://github.com/iquidus/explorer/issues/56

**Closed by TheHolyRoger** 2019-12-25 01:14 UTC
