### ISSUE TITLE
Does iquidus support shadowcoin ?  THX

### ISSUE THREAD

**Issue by storm2020** [iquidus/explorer#71] opened 2017-03-22 14:35 UTC
1. start *coind with -daemon -txindex; 
2. sync block data to mongo, bug it crash as below; 
root@iZbp13nt8kqxx16dulf7loZ:/data1/explorer# /bin/node scripts/sync.js index update 
script launched with pid: 15669
/data1/explorer/lib/database.js:642
              lib.syncLoop(block.tx.length, function (subloop) {
                                   ^
TypeError: Cannot read property 'length' of undefined
    at /data1/explorer/lib/database.js:642:36
    at Request._callback (/data1/explorer/lib/explorer.js:107:14)
    at Request.self.callback (/data1/explorer/node_modules/request/request.js:187:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/data1/explorer/node_modules/request/request.js:1044:10)
    at Request.emit (events.js:107:17)
    at IncomingMessage.<anonymous> (/data1/explorer/node_modules/request/request.js:965:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
3. npm console show this error. So does iquidus support shadowcoin ?  Many thanks.
{ [Error: Invalid params, response status code: 401] code: -32602 }
GET /api/getblockcount 200 28ms - 39b
{ [Error: Invalid params, response status code: 401] code: -32602 }
GET /api/getconnectioncount 200 14ms - 39b
{ [Error: Invalid params, response status code: 401] code: -32602 }
GET /api/getblockhash?height=1 200 4ms - 39b
{ [Error: Invalid params, response status code: 401] code: -32602 }
GET /api/getblock?hash=There%20was%20an%20error.%20Check%20your%20console. 200 2ms - 39b

**Comment by TheHolyRoger** [comment] 2019-12-25 01:38
Duplicate of https://github.com/iquidus/explorer/issues/56

**Closed by TheHolyRoger** 2019-12-25 01:38 UTC
