### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by MyWay** [iquidus/explorer#87] opened 2017-07-21 10:18 UTC
````
node --stack-size=15000 scripts/sync.js index reindex
````
Then I get:
````
script launched with pid: 24514  
index cleared (reindex)
/dir/explorer/lib/database.js:642
              lib.syncLoop(block.tx.length, function (subloop) {
                                   ^

TypeError: Cannot read property 'length' of undefined
    at /dir/explorer/lib/database.js:642:36
    at Request._callback (/dir/explorer/lib/explorer.js:107:14)
    at Request.self.callback (/dir/explorer/node_modules/request/request.js:187:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/dir/explorer/node_modules/request/request.js:1044:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/dir/explorer/node_modules/request/request.js:965:12)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
````

**Comment by Beirdo** [comment] 2017-10-19 05:41
+1

I am getting exactly this (on a peercoin clone)

**Comment by lutsifer** [comment] 2017-11-23 18:47
any solution?

**Comment by modInfo** [comment] 2018-01-03 06:19
how to fix it?

**Comment by bigwavedave42** [comment] 2018-01-29 08:06
+1

**Comment by complexiflow** [comment] 2018-02-22 15:23
Anybody a solution for this problem?

**Comment by erfan007p** [comment] 2018-02-22 15:53
Check your daemon, rpc info, or mongod

**Comment by aitorp6** [comment] 2018-03-04 22:23
Same problem here. anybody has the solution?

**Comment by GiorgosK** [comment] 2018-03-17 15:08
same problem with a POS coin
daemon is running, can connect to rpc locally and from the internet, and mongodb can be accessed from explorer and it contains info that were taken from `DAEMON getinfo` command

I suspect it has to do with a misinstalled library, anybody found a solution ?

**Comment by vm06007** [comment] 2018-03-21 22:16
same issue here, any update?

**Comment by uaktags** [comment] 2019-06-25 18:28
Closing due to no movement in some time.

If someone is still having this issue, please try some debugging on this:
-- ``console.log(block)`` on line /dir/explorer/lib/database.js:642 would tell you what block is. It's pretty obvious that the issue is that block.tx is empty which it shouldn't be, so there's an issue there with the data being provided back from the daemon. Find out what block this is (should be block 1 just after genesis). You can validate that in database.js as well in the same area by checking what number x is on.

**Closed by uaktags** 2019-06-25 18:28 UTC
