### ISSUE TITLE
Saved peers missing ports or country, dropping peers. Re-reun this script afterwards.

### ISSUE THREAD

**Issue by lurchinms** [iquidus/explorer#459] opened 2021-04-30 12:01 UTC
Here is my data:
[{"id":0,"addr":"159.203.80.106","addrlocal":"209.145.58.82:54492","addrbind":"209.145.58.82:54492","services":"000000000000040

**Comment by joeuhren** [comment] 2021-05-06 18:44
It seems that your data is missing the `version` and `subver` values that the explorer is expecting.

Which coin is this for?

**Comment by lurchinms** [comment] 2021-05-06 22:14
Titcoin 
https://github.com/titcoin
http://explorer.kriptokyng.com:3001/
Sometime the nodes are list and sometimes they are not.

**Comment by joeuhren** [comment] 2021-05-08 22:57
I took a look and am not able to reproduce the same problem you are having. I checked your explorer periodically and can confirm that sometimes it shows peers on the network page and sometimes it doesn't, so I can see you are having issues, I just can't replicate them.

One thing I notice is that your explorer always has 18-19 connections to the network, but yet when I run my own node I cannot find more than 5 peers to connect to. Not only that, but I crawled the network and found there are almost no peers to be found, only those 5 that I found the first time. I did this test on a couple different machines with different IP addresses and capabilities (IPv6) and the result is the same.

I downloaded the 0.16.3 Update 4 wallet from https://github.com/titcoin/titcoin/releases/download/v0.16.3-titcoin4/titcoin-0.16.3.4.tar.gz . Is that the newest version? And is it possible you are using a different wallet for your explorer? That's one of the only things I can think of that could be different here.

Another thing that would help is if you would be able to post a copy of your peers.dat file so that I can try it with my own node to see what additional peers I might be able to connect to with that. Either that or else when you notice the explorer is having problems displaying the peers on the website, you can try dumping the list of peers and post the full list here as well so that I can see what the data looks like to help pinpoint the issue. Use `titcoin-cli getpeerinfo` to get that data.

**Comment by uaktags** [comment] 2021-07-16 00:22
Closing since the explorer is now defunct.

**Closed as completed by uaktags** 2021-07-16 00:22 UTC
