### ISSUE TITLE
Unspent outputs API?

### ISSUE THREAD

**Issue by anoxxxy** [iquidus/explorer#95] opened 2017-08-30 08:13 UTC
Hello,
I would like to retrieve Unspent outputs of an address.
I have looked through the API and cannot seem to find anything to list the unspent outputs.

chainz.cryptoid.info has a similar API to retrieve the unspent outputs.

[https://chainz.cryptoid.info/bay/api.dws?q=unspent&active=bKP9kPDRU3KSiRCLXnMHNFLjoeYHEcPRYh&key=b8d99d015bfd&_=1504080509426](https://chainz.cryptoid.info/bay/api.dws?q=unspent&active=bKP9kPDRU3KSiRCLXnMHNFLjoeYHEcPRYh&key=b8d99d015bfd&_=1504080509426)
Which gives us the following information:

```
{

    "unspent_outputs": [
        {
            "tx_hash": "5588ede3260115a9b8fea1abca3a01570fd116726d8c04e23be9bbd8b9711c71",
            "tx_ouput_n": 0,
            "value": "30900000",
            "confirmations": 20682,
            "script": "76a91448fac3694683c2cd42663fe9c0f0504907a0d65988ac"
        },
        {
            "tx_hash": "5588ede3260115a9b8fea1abca3a01570fd116726d8c04e23be9bbd8b9711c71",
            "tx_ouput_n": 1,
            "value": "200000",
            "confirmations": 20682,
            "script": "76a91448fac3694683c2cd42663fe9c0f0504907a0d65988ac"
        },
        {
            "tx_hash": "0dbbd28d97c285e3aa48b929ad0456901ff9d268f1908146f7514d9ed7039ece",
            "tx_ouput_n": 1,
            "value": "30000000",
            "confirmations": 17414,
            "script": "76a91448fac3694683c2cd42663fe9c0f0504907a0d65988ac"
        },
        {
            "tx_hash": "1ec7903e0d472a69241a4c917d336e289d19eee000583cc1947bdcb04e7785c1",
            "tx_ouput_n": 1,
            "value": "40000000",
            "confirmations": 17414,
            "script": "76a91448fac3694683c2cd42663fe9c0f0504907a0d65988ac"
        },
        {
            "tx_hash": "cc84bc3335c207070433f8e8347ec7821d814f127debd788eaca84ecce62dfb3",
            "tx_ouput_n": 1,
            "value": "20000000",
            "confirmations": 17414,
            "script": "76a91448fac3694683c2cd42663fe9c0f0504907a0d65988ac"
        },
        {
            "tx_hash": "2901e410955ece04e63ae5f921b38de1546b4b172da4b62f6680a71968a32a7e",
            "tx_ouput_n": 1,
            "value": "10000000",
            "confirmations": 17414,
            "script": "76a91448fac3694683c2cd42663fe9c0f0504907a0d65988ac"
        },
        {
            "tx_hash": "62d193e988ce084ef46c562b65d6b202fce6c9a24903ec6512a54491fb1ddc0d",
            "tx_ouput_n": 1,
            "value": "50000000",
            "confirmations": 17412,
            "script": "76a91448fac3694683c2cd42663fe9c0f0504907a0d65988ac"
        }
    ]

}
```

Is this possible with Iquidus Explorer?
If there isnt such a function in the API, how can I implement it.
Any advice is appreciated.

**Comment by zilveer** [comment] 2017-08-31 03:42
@anoxxxy 
I think you need to use importaddress to be able to get listunspent.

Can someone else confirm this?

**Comment by zilveer** [comment] 2017-09-11 11:51
@iquidus can you please help?

**Comment by olegmitrakhovich** [comment] 2019-08-22 17:27
yes I am also interested in adding this function, any news on this? @zilveer

**Comment by zilveer** [comment] 2020-01-22 23:12
@olegmitrakhovich unfortunately no, I hope the devs can fix it soon

**Comment by TheHolyRoger** [comment] 2020-01-23 09:23
Duplicate of #37

**Closed by TheHolyRoger** 2020-01-23 09:23 UTC
