### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined (lib/explorer.js:344)

### ISSUE THREAD

**Issue by poolerMF** [iquidus/explorer#246] opened 2018-12-04 11:10 UTC
trying to make CottonCoin explorer

```
lib/explorer.js:344
          module.exports.syncLoop(tx.vout.length, function (loop) {

TypeError: Cannot read property 'length' of undefined
    at lib/explorer.js:344:43
    at Request._callback (lib/explorer.js:114:14)
    at Request.self.callback (node_modules/request/request.js:187:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (node_modules/request
...
```

I solved id by replacing line 344:
from:
`if (tx) {`
to:
`if (tx && tx.vout) {`

**is it OK ?**

I also had problem https://github.com/iquidus/explorer/issues/78, but solved it with https://github.com/iquidus/explorer/issues/78#issuecomment-368241329

**Comment by TheHolyRoger** [comment] 2019-12-25 01:13
Duplicate of https://github.com/iquidus/explorer/issues/56

**Closed by TheHolyRoger** 2019-12-25 01:13 UTC
